/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.Produto;

/**
 *
 * @author marcelo
 */
public class ListarProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarProduto
     */
    public ListarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeListar = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);

        jLabel1.setText("Nome do produto:");

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Id do produto", "Marca", "Modelo", "Preço", "Descrição", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(tableProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeListar, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar)
                    .addComponent(btnBuscar))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        setBounds(0, 0, 727, 395);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        List<Produto> listaProdutos;
        
        Produto p = new Produto();
        

        listaProdutos = p.listar("/home/marcelo/Área de Trabalho/JavaLista/repositorioProjeto/listaDeProduto.dat");
                
        Vector colunas = new Vector();
        colunas.add("Nome");
        colunas.add("Id do produto");
        colunas.add("Marca");
        colunas.add("Modelo");
        colunas.add("Preco");
        colunas.add("Descricao");
        
        Vector data = new Vector();
        for(Produto a1 : listaProdutos){
            Vector linhas = new Vector();
            linhas.add(a1.getNomeProduto());
            linhas.add(a1.getIdProduto());
            linhas.add(a1.getMarca());
            linhas.add(a1.getModelo());
            linhas.add(a1.getPreco());
            linhas.add(a1.getDescricao());
            data.add(linhas);
        }
        DefaultTableModel tblModel = new DefaultTableModel(data,colunas);
        tableProdutos.setModel(tblModel);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        List<Produto> listaProdutos;
        
        Produto p = new Produto();
        

        listaProdutos = p.listar("/home/marcelo/Área de Trabalho/JavaLista/repositorioProjeto/listaDeProduto.dat");
                
        Vector colunas = new Vector();
        colunas.add("Nome");
        colunas.add("Id do produto");
        colunas.add("Marca");
        colunas.add("Modelo");
        colunas.add("Preco");
        colunas.add("Descricao");
        
        Vector data = new Vector();
        for(Produto a1 : listaProdutos){
           if(a1.getNomeProduto().equalsIgnoreCase(txtNomeListar.getText())){
            Vector linhas = new Vector();
            linhas.add(a1.getNomeProduto());
            linhas.add(a1.getIdProduto());
            linhas.add(a1.getMarca());
            linhas.add(a1.getModelo());
            linhas.add(a1.getPreco());
            linhas.add(a1.getDescricao());
            data.add(linhas);
           }
        }
        DefaultTableModel tblModel = new DefaultTableModel(data,colunas);
        tableProdutos.setModel(tblModel);
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField txtNomeListar;
    // End of variables declaration//GEN-END:variables
}
